@startuml TodoList
   entity User {
      * id: integer <<PK>>
      --
      * userName : string
      * password : string
      * role : enum ('admin', 'user')
   }

   entity SocialLogin {
      * id : integer <<PK>>
      --
      * socialType: string
      * userId: integer <<FK>>
      * userName: string
      * password: string
   }

   entity Project {
      * id: integer <<PK>>
      --
      * projectName : string
   }

   entity Project_User {
      * id: integer <<PK>>
      * projectId : integer <<FK>>
      * userId: integer <<FK>>
   }

   entity Task {
      * id : integer <<PK>>
      --
      * title: string
      * description: string
      * projectId : integer <<FK>>
      * userId : integer <<FK>
      * isDone: boolean
      * isClearn:boolean
      * linkTaskId: integer
   }

   Project ||--|{ Task
   Project }|--|| Project_User
   User }|--|| Project_User
   User }|--|| Task
   User }|--|| SocialLogin
   Task |o--o| Task

@enduml
